### ISSUE TITLE
dashboard yarn run start will produce compile errors

### ISSUE THREAD

**Issue by litong01** [hyperledger/cello#157]
After yarn install, I ran yarn run start.
## Expected Behavior
The dashboard app will start up and ready to take requests.

## Current Behavior
Compile errors occur
## Steps to Reproduce
1. have clean cello cloned
2. go to cello/src/dashboard directory
3. yarn install
4. yarn run start

Then the error will appear.

Error occurred compiling file /home/ubuntu/hl/src/github.com/cello/src/dashboard/src/pages/Operator/styles.less
Error LessError: Cannot find module '@/utils/utils.less' from '/home/ubuntu/hl/src/github.com/cello/src/dashboard/src/pages/Operator'
    at module.exports (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less-plugin-npm-import/node_modules/resolve/lib/sync.js:33:11)
    at NpmFileManager.resolve (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less-plugin-npm-import/lib/npm-file-manager.js:29:16)
    at NpmFileManager.loadFile (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less-plugin-npm-import/lib/npm-file-manager.js:52:29)
    at ImportManager.push (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:10235:39)
    at ImportVisitor.processImportNode (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:5144:28)
    at ImportVisitor.visitImport (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:5109:22)
    at Visitor.visit (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:4924:32)
    at Visitor.visitArray (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:4955:22)
    at Ruleset.accept (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:1911:34)
    at Visitor.visit (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:4938:22)
    at ImportVisitor.run (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:5085:27)
    at Object.parse (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:6803:22)
    at Object.parse (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:10516:18)
    at Object.render (/home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:10276:18)
    at /home/ubuntu/hl/src/github.com/cello/src/dashboard/node_modules/less/dist/less.cjs.js:10265:24
    at new Promise (<anonymous>) {
  type: 'Syntax',
  filename: '/home/ubuntu/hl/src/github.com/cello/src/dashboard/src/pages/Operator/styles.less',
  index: 157,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    "@import '~antd/lib/style/themes/default.less';",
    "@import '~@/utils/utils.less';",
    ''
  ]
}

**Comment by litong01** [comment]
The app will start and can hit the url and the user interface appears to be working correctly.
