### ISSUE TITLE
新建网络时出错

### ISSUE THREAD

**Issue by neo0591** [hyperledger/cello#529]
使用1.0.00rc版本，创建网络后，页面上提示创建成功，但是api-engine容器报错，再配置通道也是失败
## Current Behavior
注册新账号和组织，配置代理和节点成功，然后新建网络
## Steps to Reproduce

1.注册新账号和组织
2.配置代理和节点成功
3.新建网络，提示成功，后台报错
4.新建通道，提示失败

## Context (Environment)

* OS: Ubuntu 20.04
* Architecture:
* Docker version:  24.0.2
* Docker compose version: 1.29.2
* Kubernetes version:

## Detailed Description and log
2023-06-25 05:05:01.417 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2023-06-25 05:05:01.443 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2023-06-25 05:05:01.443 UTC [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: /opt/cello/linkcircle/configtx.yaml
2023-06-25 05:05:01.449 UTC [common.tools.configtxgen] doOutputBlock -> INFO 004 Generating genesis block
2023-06-25 05:05:01.454 UTC [common.tools.configtxgen] doOutputBlock -> INFO 005 Writing genesis block
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/server/api/routes/network/views.py", line 160, in _start_node
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    raise e
  File "/var/www/server/api/routes/network/views.py", line 158, in _start_node
    raise ResourceNotFound(detail="Container Not Built")
api.exceptions.ResourceNotFound: Container Not Built
    self._target(*self._args, **self._kwargs)
  File "/var/www/server/api/routes/network/views.py", line 160, in _start_node
    raise e
  File "/var/www/server/api/routes/network/views.py", line 158, in _start_node
    raise ResourceNotFound(detail="Container Not Built")
api.exceptions.ResourceNotFound: Container Not Built
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/server/api/routes/network/views.py", line 160, in _start_node
    raise e
  File "/var/www/server/api/routes/network/views.py", line 158, in _start_node
    raise ResourceNotFound(detail="Container Not Built")
api.exceptions.ResourceNotFound: Container Not Built
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/server/api/routes/network/views.py", line 160, in _start_node
    raise e
  File "/var/www/server/api/routes/network/views.py", line 158, in _start_node
    raise ResourceNotFound(detail="Container Not Built")
api.exceptions.ResourceNotFound: Container Not Built
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/server/api/routes/network/views.py", line 160, in _start_node
    raise e
  File "/var/www/server/api/routes/network/views.py", line 158, in _start_node
    raise ResourceNotFound(detail="Container Not Built")
api.exceptions.ResourceNotFound: Container Not Built
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/server/api/routes/network/views.py", line 160, in _start_node
    raise e
  File "/var/www/server/api/routes/network/views.py", line 158, in _start_node
    raise ResourceNotFound(detail="Container Not Built")
api.exceptions.ResourceNotFound: Container Not Built

**Comment by xichen1** [comment]
请问cello-docker-agent这个容器有没有报错？

**Comment by neo0591** [comment]
你好，感谢回复，我找到问题原因了，在节点配置后，状态是未启动，需要等待几分钟，节点都启动完成后，再配置网络就没有问题。
